import {
  Bath,
  BedDouble,
  Headphones,
  HeartHandshake,
  Home,
  MessageCircleHeart,
  Music,
  Sparkles,
  Utensils,
  Wind,
} from "lucide-react";
import type { ComponentType } from "react";

export type RecoveryStyle = "music" | "senses" | "body" | "emotion" | "space" | "connection" | "rest";

export type Option = {
  id: string;
  label: string;
  detail: string;
  score: number;
  styles?: RecoveryStyle[];
};

export type Question = {
  id: string;
  eyebrow: string;
  title: string;
  options: Option[];
};

export type Action = {
  title: string;
  time: string;
  level: 1 | 2 | 3;
  styles: RecoveryStyle[];
  body: string;
  steps: string[];
  icon: ComponentType<{ size?: number; strokeWidth?: number }>;
};

export type ResultLevel = {
  id: string;
  min: number;
  max: number;
  name: string;
  tone: string;
  summary: string;
  description: string;
  focus: string;
  actionLevels: Array<Action["level"]>;
  priorityStyles: RecoveryStyle[];
  avoidList: string[];
};

export const questions: Question[] = [
  {
    id: "mood",
    eyebrow: "기분의 날씨",
    title: "오늘 마음은 어떤 쪽에 가까워?",
    options: [
      { id: "cloudy", label: "조금 흐림", detail: "가라앉긴 했지만 움직일 여지는 있어.", score: 1, styles: ["senses"] },
      { id: "flat", label: "아무것도 하기 싫음", detail: "해야 할 일이 보여도 몸이 잘 안 따라와.", score: 2, styles: ["rest", "body"] },
      { id: "heavy", label: "이유 없이 무거움", detail: "마음 한쪽이 계속 눌려 있는 느낌이야.", score: 3, styles: ["emotion"] },
      { id: "numb", label: "감정이 거의 안 느껴짐", detail: "좋고 싫음도 멀어진 것 같아.", score: 4, styles: ["senses", "connection"] },
    ],
  },
  {
    id: "energy",
    eyebrow: "몸 배터리",
    title: "지금 몸의 에너지는 어느 정도야?",
    options: [
      { id: "sixty", label: "60% 이상", detail: "작게 시작하면 꽤 할 수 있을 것 같아.", score: 0, styles: ["body", "space"] },
      { id: "thirty", label: "30~60%", detail: "쉬운 일 하나 정도는 가능해.", score: 1, styles: ["senses"] },
      { id: "ten", label: "10~30%", detail: "일어나기까지 시간이 필요해.", score: 3, styles: ["rest"] },
      { id: "zero", label: "거의 0%", detail: "누워 있는 것 말고는 어렵게 느껴져.", score: 4, styles: ["rest", "connection"] },
    ],
  },
  {
    id: "thoughts",
    eyebrow: "머릿속 소리",
    title: "생각은 어떤 모양으로 돌고 있어?",
    options: [
      { id: "messy", label: "조금 복잡함", detail: "정리는 안 됐지만 견딜 만해.", score: 1, styles: ["space"] },
      { id: "loop", label: "같은 생각 반복", detail: "멈추고 싶은데 계속 되감기돼.", score: 2, styles: ["music", "body"] },
      { id: "blame", label: "나를 탓하는 생각", detail: "내가 문제인 것처럼 느껴져.", score: 3, styles: ["emotion", "connection"] },
      { id: "blank", label: "생각하기도 지침", detail: "판단하거나 고르는 것도 부담스러워.", score: 4, styles: ["rest", "senses"] },
    ],
  },
  {
    id: "routine",
    eyebrow: "기본 루틴",
    title: "최근 잠, 식사, 씻기는 어땠어?",
    options: [
      { id: "kept", label: "대체로 유지됨", detail: "완벽하진 않아도 기본은 챙겼어.", score: 0, styles: ["body"] },
      { id: "loose", label: "조금 흐트러짐", detail: "한두 가지가 자주 밀려.", score: 1, styles: ["space", "senses"] },
      { id: "broken", label: "많이 무너짐", detail: "씻기나 먹기가 꽤 버거워.", score: 3, styles: ["senses", "rest"] },
      { id: "missing", label: "거의 못 챙김", detail: "기본적인 것도 시작이 안 돼.", score: 4, styles: ["connection", "rest"] },
    ],
  },
  {
    id: "people",
    eyebrow: "사람과의 거리",
    title: "지금 사람을 대하는 느낌은?",
    options: [
      { id: "talk", label: "누군가와 말하고 싶음", detail: "말하면 조금 풀릴 것 같아.", score: 0, styles: ["connection"] },
      { id: "one", label: "편한 한 명은 괜찮음", detail: "부담 없는 사람이라면 가능해.", score: 1, styles: ["connection"] },
      { id: "alone", label: "아무도 만나기 싫음", detail: "혼자 있고 싶은 마음이 커.", score: 2, styles: ["music", "space"] },
      { id: "hard", label: "연락 보는 것도 힘듦", detail: "알림 하나도 크게 느껴져.", score: 4, styles: ["rest"] },
    ],
  },
  {
    id: "bodySignal",
    eyebrow: "몸 상태",
    title: "지금 몸 상태는 어디에 가까워?",
    options: [
      { id: "tight", label: "긴장돼서 몸이 뻣뻣해", detail: "목, 어깨, 얼굴 쪽이 굳어 있거나 힘이 잘 안 빠져.", score: 1, styles: ["body", "senses"] },
      { id: "slow", label: "몸이 무겁고 느려", detail: "일어나거나 움직이기까지 시간이 오래 걸려.", score: 2, styles: ["body", "rest"] },
      { id: "messy", label: "속이 불편하거나 입맛이 없어", detail: "먹는 것부터 막히고 몸 컨디션이 애매해.", score: 3, styles: ["body", "senses"] },
      { id: "shut", label: "내 몸 상태를 잘 모르겠어", detail: "배고픈지 피곤한지, 뭐가 불편한지도 잘 구분이 안 돼.", score: 4, styles: ["rest", "connection"] },
    ],
  },
  {
    id: "craving",
    eyebrow: "회복 취향",
    title: "지금 이 중에서 제일 덜 부담스러운 건 뭐야?",
    options: [
      { id: "sound", label: "익숙한 노래 하나 틀어두기", detail: "가사를 따라 부르지 않아도 되고, 그냥 배경에 깔아두는 정도.", score: 0, styles: ["music"] },
      { id: "warm", label: "따뜻한 물이나 향을 느끼기", detail: "샤워까지는 아니어도 손 씻기, 따뜻한 차, 핸드크림 정도는 가능해.", score: 0, styles: ["senses"] },
      { id: "tiny", label: "눈앞의 물건 3개만 치우기", detail: "방 전체 말고 컵, 휴지, 옷처럼 바로 보이는 것만 옆으로 빼기.", score: 0, styles: ["space"] },
      { id: "none", label: "누가 하나만 정해줬으면 좋겠어", detail: "고르는 것도 피곤해서 가장 쉬운 행동 하나만 받고 싶어.", score: 2, styles: ["rest"] },
    ],
  },
  {
    id: "duration",
    eyebrow: "지속 시간",
    title: "이런 상태가 얼마나 이어졌어?",
    options: [
      { id: "today", label: "오늘 갑자기", detail: "어제와 비교하면 오늘 유독 가라앉았어.", score: 0, styles: ["senses", "music"] },
      { id: "few", label: "며칠째", detail: "짧게 끝날 줄 알았는데 며칠 이어지고 있어.", score: 1, styles: ["space", "body"] },
      { id: "week", label: "일주일 안팎", detail: "일상 루틴에도 슬슬 영향이 있어.", score: 2, styles: ["rest", "connection"] },
      { id: "long", label: "2주 이상", detail: "혼자 넘기기 어렵다는 생각이 들어.", score: 3, styles: ["connection", "rest"] },
    ],
  },
  {
    id: "wish",
    eyebrow: "지금 필요한 것",
    title: "오늘 가장 받고 싶은 도움은 뭐야?",
    options: [
      { id: "restart", label: "다시 시작하는 신호", detail: "작은 의식처럼 몸을 깨우고 싶어.", score: 0, styles: ["body", "senses"] },
      { id: "comfort", label: "나를 덜 미워하는 말", detail: "내 편이 되는 문장이 필요해.", score: 1, styles: ["emotion"] },
      { id: "quiet", label: "조용한 회복 공간", detail: "자극을 줄이고 숨을 고르고 싶어.", score: 1, styles: ["rest", "space"] },
      { id: "signal", label: "혼자가 아니라는 신호", detail: "길게 말하지 않아도 연결되고 싶어.", score: 2, styles: ["connection"] },
    ],
  },
];

export const resultLevels: ResultLevel[] = [
  {
    id: "cloud",
    min: 0,
    max: 8,
    name: "살짝 우웅 모드",
    tone: "오늘의 우웅은 아직 작은 버튼으로 꺼볼 수 있는 정도예요.",
    summary: "기분이 내려앉긴 했지만, 짧은 행동 하나로 흐름을 살짝 틀 여지가 있어요.",
    description: "거창한 회복 말고 5~10분짜리 전환이 맞아요. 노래 하나, 조명 하나, 창문 2분 같은 작은 스위치를 먼저 눌러봅시다.",
    focus: "작은 스위치 켜기",
    actionLevels: [1, 2, 3],
    priorityStyles: ["music", "senses", "space", "body"],
    avoidList: ["기분 분석 길게 하기", "새 콘텐츠 무한 스크롤", "갑자기 방 전체 갈아엎기"],
  },
  {
    id: "battery",
    min: 9,
    max: 16,
    name: "배터리 23% 모드",
    tone: "지금은 풀파워 금지. 저전력 모드로 가는 게 맞아요.",
    summary: "무기력감이 꽤 올라와 있어서 긴 과제는 앱 강제종료처럼 느껴질 수 있어요.",
    description: "오늘은 잘하려고 하지 말고 덜 망가지는 쪽으로 갑니다. 물, 옷, 알림, 침대처럼 바로 손댈 수 있는 것부터 추천할게요.",
    focus: "저전력으로 굴러가기",
    actionLevels: [1, 2],
    priorityStyles: ["body", "senses", "space", "rest"],
    avoidList: ["할 일 몰아서 처리하기", "답장 한 번에 다 하기", "운동으로 기분 역전 노리기"],
  },
  {
    id: "pause",
    min: 17,
    max: 25,
    name: "로딩 중 우웅 모드",
    tone: "마음이 빙글빙글 로딩 중이라 복잡한 선택지는 잠깐 치워야 해요.",
    summary: "감정, 몸, 루틴이 같이 느려져서 '뭐라도 해야지'가 오히려 부담이 될 수 있어요.",
    description: "오늘은 생각으로 설득하지 말고 자동화된 행동으로 갑니다. 물 마시기, 발 내리기, 알림 끄기처럼 판단이 거의 필요 없는 것부터요.",
    focus: "선택지 1개만 남기기",
    actionLevels: [1],
    priorityStyles: ["rest", "senses", "body", "connection"],
    avoidList: ["큰 결심으로 시작하기", "왜 이러지 계속 파고들기", "선택지 많은 앱 켜기"],
  },
  {
    id: "urgent",
    min: 26,
    max: 34,
    name: "혼자 두면 안 되는 우웅",
    tone: "이 정도 우웅은 혼자서만 상대하기엔 난이도가 높아요.",
    summary: "마음 에너지가 많이 낮고, 기본적인 행동도 시작하기 어려울 수 있어요.",
    description: "오늘 목표는 멋지게 회복하기가 아니라 안전하게 지나가기예요. 난이도 1 행동과 연결 신호를 먼저 추천합니다.",
    focus: "안전 먼저, 다음은 연결",
    actionLevels: [1],
    priorityStyles: ["connection", "rest", "body", "senses"],
    avoidList: ["혼자 괜찮은 척 버티기", "위험한 생각을 혼자 붙잡고 있기", "도움 요청을 내일로 미루기"],
  },
];

export const actions: Action[] = [
  {
    title: "기분 전환곡 7개만 고르기",
    time: "12분",
    level: 2,
    styles: ["music", "emotion"],
    body: "새 노래를 찾지 말고 이미 아는 곡만 고른다. 기준은 들었을 때 몸이 덜 무거운 곡이다.",
    steps: ["최근 들은 곡 목록 열기", "넘기지 않고 들을 수 있는 곡 7개 저장하기", "첫 곡은 가장 익숙한 곡으로 배치하기"],
    icon: Music,
  },
  {
    title: "30분 꼼꼼 샤워",
    time: "30분",
    level: 3,
    styles: ["senses", "body"],
    body: "대충 씻고 끝내지 말고 순서를 정해서 천천히 씻는다. 끝나면 옷까지 갈아입는다.",
    steps: ["따뜻한 물을 어깨에 3분 맞기", "머리, 얼굴, 몸 순서로 씻기", "수건으로 말린 뒤 바로 깨끗한 옷 입기"],
    icon: Bath,
  },
  {
    title: "침대 위 한 칸 비우기",
    time: "7분",
    level: 1,
    styles: ["space", "rest"],
    body: "방 전체를 건드리지 않는다. 누울 자리만 확보한다.",
    steps: ["침대 위 물건을 바닥 한쪽에만 모으기", "이불을 크게 한 번 털기", "베개 방향을 바꾸고 다시 눕기"],
    icon: BedDouble,
  },
  {
    title: "현재 상태 한 줄 기록",
    time: "5분",
    level: 1,
    styles: ["emotion", "rest"],
    body: "긴 일기는 부담이 크다. 지금 상태를 관찰하듯 한 줄만 적는다.",
    steps: ["메모장 열기", "'지금 상태:' 뒤에 한 문장 쓰기", "원인 분석은 하지 않고 저장하기"],
    icon: Sparkles,
  },
  {
    title: "편의점 생존 메뉴 고르기",
    time: "15분",
    level: 2,
    styles: ["body", "senses"],
    body: "완벽한 식사 말고 지금 먹을 수 있는 조합을 만든다.",
    steps: ["따뜻한 것 1개 고르기", "씹기 쉬운 것 1개 고르기", "물이나 이온음료처럼 넘기기 쉬운 것 더하기"],
    icon: Utensils,
  },
  {
    title: "알림 없는 10분",
    time: "10분",
    level: 1,
    styles: ["rest", "space"],
    body: "기분을 좋게 만들려 하지 않고, 들어오는 자극만 잠깐 줄인다.",
    steps: ["방해금지 모드 켜기", "휴대폰을 뒤집어두기", "타이머 10분 맞추기"],
    icon: Wind,
  },
  {
    title: "카톡 말투로 3줄 쓰기",
    time: "6분",
    level: 1,
    styles: ["emotion", "connection"],
    body: "일기처럼 쓰지 말고 친구에게 보내는 말투로 짧게 쓴다. 실제로 보내지 않아도 된다.",
    steps: ["'오늘 좀 별로인 이유는'으로 시작하기", "3줄을 넘기지 않기", "저장만 하고 닫기"],
    icon: MessageCircleHeart,
  },
  {
    title: "새 콘텐츠 찾지 않기",
    time: "20분",
    level: 1,
    styles: ["music", "rest"],
    body: "추천 피드를 넘기지 않는다. 이미 저장해둔 것 하나만 다시 본다.",
    steps: ["저장 목록 열기", "이미 본 영상 하나 재생하기", "댓글과 추천 영상은 보지 않기"],
    icon: Headphones,
  },
  {
    title: "세수, 양말, 립밤",
    time: "8분",
    level: 1,
    styles: ["body", "senses"],
    body: "밖에 나가지 않아도 되는 최소 리셋 세트다.",
    steps: ["양말 갈아신기", "세수하거나 손목까지 씻기", "립밤이나 핸드크림 바르기"],
    icon: Sparkles,
  },
  {
    title: "이모티콘 하나 보내기",
    time: "3분",
    level: 1,
    styles: ["connection", "rest"],
    body: "상황 설명을 길게 하지 않는다. 대화가 가능한 사람에게 표시만 남긴다.",
    steps: ["가장 덜 부담스러운 대화방 열기", "말 대신 이모티콘 하나만 보내기", "보낸 뒤 알림을 20분 꺼두기"],
    icon: HeartHandshake,
  },
  {
    title: "방 조건 하나만 바꾸기",
    time: "5분",
    level: 1,
    styles: ["space", "senses"],
    body: "공간 전체를 바꾸지 않고 온도, 빛, 공기 중 하나만 바꾼다.",
    steps: ["창문을 2분만 열기 또는 닫기", "조명을 하나 끄거나 켜기", "몸에 닿는 천 하나를 바꾸기"],
    icon: Home,
  },
  {
    title: "도움 요청 문장 복사하기",
    time: "4분",
    level: 1,
    styles: ["connection", "emotion"],
    body: "직접 문장을 만들기 어렵다면 아래 문장을 그대로 쓴다. 보내는 건 다음 단계다.",
    steps: ["'나 오늘 상태가 많이 안 좋아서 혼자 있기 힘들어' 복사하기", "보낼 사람 한 명만 떠올리기", "가능하면 보내고, 어렵다면 메모에 저장하기"],
    icon: HeartHandshake,
  },
  {
    title: "물 300ml 마시기",
    time: "3분",
    level: 1,
    styles: ["body", "senses"],
    body: "목마름을 느끼지 못해도 먼저 물을 마신다. 카페인 음료는 제외한다.",
    steps: ["컵이나 텀블러에 물 따르기", "한 번에 다 마시지 말고 세 번 나눠 마시기", "마신 뒤 컵을 싱크대에 두기"],
    icon: Utensils,
  },
  {
    title: "상단 알림 10개 지우기",
    time: "4분",
    level: 1,
    styles: ["space", "rest"],
    body: "밀린 일을 처리하지 않는다. 눈에 보이는 알림만 줄인다.",
    steps: ["휴대폰 상단 알림창 열기", "답장하지 않을 알림 10개 지우기", "남은 알림은 그대로 두기"],
    icon: Home,
  },
  {
    title: "책상 위 컵만 치우기",
    time: "5분",
    level: 1,
    styles: ["space"],
    body: "정리 범위를 컵, 병, 캔으로 제한한다.",
    steps: ["컵과 병만 찾기", "싱크대나 분리수거함으로 옮기기", "책상은 더 치우지 않고 멈추기"],
    icon: Home,
  },
  {
    title: "좋아했던 곡 1절만 듣기",
    time: "4분",
    level: 1,
    styles: ["music", "rest"],
    body: "플레이리스트를 만들 힘이 없을 때 쓰는 최소 버전이다.",
    steps: ["이미 아는 곡 하나 검색하기", "1절까지만 듣기", "괜찮으면 한 곡만 더 듣기"],
    icon: Headphones,
  },
  {
    title: "옷 한 벌만 갈아입기",
    time: "6분",
    level: 1,
    styles: ["body", "senses"],
    body: "전부 갈아입지 않아도 된다. 몸에 닿는 것 하나만 바꾼다.",
    steps: ["티셔츠나 바지 중 하나 고르기", "입던 옷은 세탁 바구니 근처에 두기", "갈아입은 뒤 물 한 모금 마시기"],
    icon: Sparkles,
  },
  {
    title: "수건 따뜻하게 쓰기",
    time: "8분",
    level: 1,
    styles: ["senses", "rest"],
    body: "샤워가 부담스러울 때 얼굴과 목만 정리한다.",
    steps: ["수건에 따뜻한 물 적시기", "얼굴과 목 뒤를 30초씩 누르기", "마른 수건으로 닦기"],
    icon: Bath,
  },
  {
    title: "문 앞에 쓰레기만 두기",
    time: "5분",
    level: 1,
    styles: ["space", "body"],
    body: "버리러 나가는 것까지 하지 않아도 된다. 다음 행동이 쉬워지게 위치만 바꾼다.",
    steps: ["가장 가까운 쓰레기 하나 집기", "봉투에 넣기", "현관문 안쪽에 두기"],
    icon: Home,
  },
  {
    title: "침대에서 발만 내리기",
    time: "2분",
    level: 1,
    styles: ["body", "rest"],
    body: "일어나는 게 목표가 아니다. 몸의 자세만 바꾼다.",
    steps: ["침대 가장자리로 이동하기", "발을 바닥에 30초 두기", "가능하면 물건 하나만 집기"],
    icon: BedDouble,
  },
  {
    title: "창문 2분 열기",
    time: "2분",
    level: 1,
    styles: ["senses", "space"],
    body: "환기를 길게 하지 않아도 된다. 공기만 한 번 바꾼다.",
    steps: ["창문이나 방문 열기", "2분 타이머 맞추기", "끝나면 닫을지 말지 그때 정하기"],
    icon: Wind,
  },
  {
    title: "배달앱 저장 메뉴 보기",
    time: "7분",
    level: 1,
    styles: ["body", "rest"],
    body: "새 메뉴를 고르느라 지치지 않게 선택지를 줄인다.",
    steps: ["자주 주문한 메뉴 목록 열기", "최근에 먹고 탈 없던 메뉴만 보기", "주문하지 않아도 후보 하나 저장하기"],
    icon: Utensils,
  },
  {
    title: "읽지 않은 메시지 제목만 보기",
    time: "5분",
    level: 1,
    styles: ["connection", "space"],
    body: "답장하지 않는다. 무엇이 와 있는지만 확인한다.",
    steps: ["메신저 앱 열기", "대화방 제목만 훑기", "답장할 대화방 하나만 고정하기"],
    icon: MessageCircleHeart,
  },
  {
    title: "나중에 답장 문구 만들기",
    time: "5분",
    level: 1,
    styles: ["connection", "rest"],
    body: "바로 설명하기 어려울 때 쓸 짧은 문장을 미리 만든다.",
    steps: ["메모장에 문장 쓰기", "'지금 바로 답장은 어려워. 나중에 연락할게' 저장하기", "필요한 대화방에 붙여넣기"],
    icon: HeartHandshake,
  },
  {
    title: "노래 한 곡 동안 스트레칭",
    time: "5분",
    level: 2,
    styles: ["music", "body"],
    body: "운동으로 생각하지 않는다. 한 곡이 끝날 때까지만 목과 어깨를 푼다.",
    steps: ["3~5분짜리 노래 틀기", "목을 좌우로 천천히 돌리기", "어깨를 위로 올렸다가 내리기 10번"],
    icon: Music,
  },
  {
    title: "바닥에 떨어진 것 5개 줍기",
    time: "6분",
    level: 1,
    styles: ["space", "body"],
    body: "청소가 아니라 바닥에 보이는 것 5개만 처리한다.",
    steps: ["봉투 하나 들기", "쓰레기 또는 옷 5개만 줍기", "6개째부터는 하지 않기"],
    icon: Home,
  },
  {
    title: "조명 밝기 바꾸기",
    time: "2분",
    level: 1,
    styles: ["senses", "space"],
    body: "방 분위기를 크게 바꾸지 않고 눈에 들어오는 빛만 조절한다.",
    steps: ["천장등을 끄거나 켜기", "스탠드가 있으면 하나만 켜기", "화면 밝기를 한 단계 낮추기"],
    icon: Sparkles,
  },
  {
    title: "냉장고 앞에서 1분 고르기",
    time: "3분",
    level: 1,
    styles: ["body"],
    body: "요리하지 않는다. 바로 먹거나 마실 수 있는 것만 본다.",
    steps: ["냉장고 문 열기", "1분 안에 하나 고르기", "못 고르면 물만 마시기"],
    icon: Utensils,
  },
  {
    title: "손톱 하나만 정리하기",
    time: "5분",
    level: 1,
    styles: ["senses", "body"],
    body: "몸 관리 범위를 아주 작게 잡는다. 손 전체가 아니라 손톱 하나도 괜찮다.",
    steps: ["손 씻기", "걸리는 손톱 하나만 다듬기", "핸드크림이 있으면 손등에만 바르기"],
    icon: Sparkles,
  },
  {
    title: "침구 냄새 바꾸기",
    time: "6분",
    level: 1,
    styles: ["senses", "space"],
    body: "세탁까지 하지 않는다. 베개나 이불의 냄새만 바꾼다.",
    steps: ["베개 커버를 뒤집거나 교체하기", "섬유탈취제를 한 번만 뿌리기", "창문 근처에서 3분 두기"],
    icon: BedDouble,
  },
  {
    title: "최악의 시간대 하나 표시",
    time: "5분",
    level: 1,
    styles: ["emotion", "rest"],
    body: "오늘 전체를 평가하지 않는다. 특히 힘든 시간대를 하나만 표시한다.",
    steps: ["메모장에 시간대 하나 쓰기", "그 시간에 할 일을 줄이기", "알림 하나를 그 시간 이후로 미루기"],
    icon: Wind,
  },
  {
    title: "내일 할 일 하나 삭제",
    time: "6분",
    level: 2,
    styles: ["emotion", "space"],
    body: "할 일을 추가하지 않는다. 내일 목록에서 하나를 지운다.",
    steps: ["내일 할 일 목록 열기", "안 해도 큰일 안 나는 것 하나 찾기", "삭제하거나 다음 주로 이동하기"],
    icon: Home,
  },
  {
    title: "귀에 익은 목소리 틀기",
    time: "15분",
    level: 1,
    styles: ["music", "connection"],
    body: "대화를 직접 하지 않아도 된다. 익숙한 팟캐스트나 영상의 목소리를 배경에 둔다.",
    steps: ["이미 들어본 콘텐츠 고르기", "화면은 보지 않아도 되게 틀기", "15분 뒤 계속 들을지 정하기"],
    icon: Headphones,
  },
  {
    title: "세탁물 5개만 분리",
    time: "7분",
    level: 1,
    styles: ["space", "body"],
    body: "빨래를 시작하지 않는다. 바닥이나 의자에 있는 옷 5개만 분리한다.",
    steps: ["세탁 바구니나 봉투 준비하기", "옷 5개만 넣기", "세탁기는 돌리지 않아도 됨"],
    icon: Home,
  },
  {
    title: "따뜻한 음료 손에 들기",
    time: "8분",
    level: 1,
    styles: ["senses", "rest"],
    body: "마시는 것보다 손에 온도를 느끼는 게 목표다.",
    steps: ["따뜻한 물이나 차 만들기", "컵을 양손으로 30초 잡기", "가능하면 세 모금 마시기"],
    icon: Utensils,
  },
  {
    title: "밖 소리 3개 찾기",
    time: "4분",
    level: 1,
    styles: ["senses", "rest"],
    body: "생각을 멈추려고 애쓰지 않고, 들리는 소리만 세어본다.",
    steps: ["눈을 감거나 시선을 낮추기", "가장 가까운 소리 하나 찾기", "조금 먼 소리 두 개 더 찾기"],
    icon: Wind,
  },
  {
    title: "사진첩에서 안전한 사진 5장 보기",
    time: "6분",
    level: 1,
    styles: ["emotion", "rest"],
    body: "추억 정리를 하지 않는다. 부담 없는 사진만 빠르게 본다.",
    steps: ["사진첩에서 음식이나 장소 사진 찾기", "불편한 사진은 바로 넘기기", "괜찮은 사진 5장만 보기"],
    icon: Sparkles,
  },
  {
    title: "의자에 앉아 발바닥 누르기",
    time: "5분",
    level: 1,
    styles: ["body", "senses"],
    body: "몸을 크게 움직이지 않고 발바닥 감각만 확인한다.",
    steps: ["의자에 앉기", "양발을 바닥에 붙이기", "발가락에 힘을 줬다 풀기 10번"],
    icon: BedDouble,
  },
  {
    title: "메일함 숫자만 줄이기",
    time: "8분",
    level: 2,
    styles: ["space"],
    body: "메일을 읽지 않는다. 광고나 알림 메일만 삭제한다.",
    steps: ["메일함 열기", "제목만 보고 광고 10개 삭제하기", "중요해 보이는 메일은 열지 않고 남기기"],
    icon: Home,
  },
  {
    title: "상태 점수만 보내기",
    time: "4분",
    level: 1,
    styles: ["connection"],
    body: "설명 대신 숫자로 보낸다. 예: 오늘 10점 만점에 3점.",
    steps: ["편한 사람 한 명 고르기", "'오늘 상태 10점 만점에 3점' 입력하기", "추가 설명은 하지 않아도 됨"],
    icon: HeartHandshake,
  },
  {
    title: "손 씻으며 물 온도 바꾸기",
    time: "3분",
    level: 1,
    styles: ["senses", "body"],
    body: "샤워가 어렵다면 손만 씻는다. 따뜻한 물과 차가운 물을 번갈아 쓴다.",
    steps: ["따뜻한 물로 20초 씻기", "차가운 물로 5초 헹구기", "수건으로 손가락 사이까지 닦기"],
    icon: Bath,
  },
  {
    title: "배경음 켜고 화면 끄기",
    time: "10분",
    level: 1,
    styles: ["music", "rest"],
    body: "영상 시청으로 넘어가지 않게 소리만 쓴다.",
    steps: ["비 오는 소리나 익숙한 음악 틀기", "화면을 끄거나 뒤집기", "10분 타이머 맞추기"],
    icon: Headphones,
  },
  {
    title: "문장 하나만 소리 내어 읽기",
    time: "3분",
    level: 1,
    styles: ["emotion", "body"],
    body: "긴 글을 읽지 않는다. 아무 문장 하나를 입 밖으로 내본다.",
    steps: ["메모나 책에서 짧은 문장 하나 고르기", "작게 한 번 읽기", "목소리가 나오면 물 한 모금 마시기"],
    icon: MessageCircleHeart,
  },
  {
    title: "장바구니에서 하나 빼기",
    time: "5분",
    level: 1,
    styles: ["space", "emotion"],
    body: "무언가를 사서 해결하려는 충동이 있을 때 선택지를 줄인다.",
    steps: ["온라인 장바구니 열기", "지금 필요 없는 것 하나 삭제하기", "앱 닫기"],
    icon: Home,
  },
  {
    title: "현관까지 갔다 오기",
    time: "4분",
    level: 2,
    styles: ["body", "space"],
    body: "외출이 목표가 아니다. 집 안에서 이동 거리만 만든다.",
    steps: ["현관까지 걷기", "신발을 신지 않고 10초 서 있기", "돌아와서 물건 하나 제자리에 두기"],
    icon: Home,
  },
  {
    title: "쉬운 약속 하나 조정하기",
    time: "8분",
    level: 2,
    styles: ["connection", "rest"],
    body: "모든 일정을 버티려 하지 않는다. 조정 가능한 것 하나를 고른다.",
    steps: ["오늘 또는 내일 일정 보기", "미뤄도 되는 약속 하나 고르기", "'오늘 컨디션이 안 좋아서 시간을 바꿀 수 있을까?' 보내기"],
    icon: HeartHandshake,
  },
  {
    title: "방문 앞에 물 두기",
    time: "3분",
    level: 1,
    styles: ["body", "space"],
    body: "나중에 마시기 쉽게 물 위치만 바꾼다.",
    steps: ["물병이나 컵 준비하기", "침대나 책상 가까이에 두기", "한 모금만 마시기"],
    icon: Utensils,
  },
  {
    title: "타이머 12분 쉬기",
    time: "12분",
    level: 1,
    styles: ["rest"],
    body: "쉬면서 다른 할 일을 찾지 않는다. 12분만 쉬는 시간을 따로 둔다.",
    steps: ["타이머 12분 설정하기", "누워도 되고 앉아도 됨", "끝나면 바로 평가하지 말고 물 한 모금 마시기"],
    icon: Wind,
  },
];
